import Head from "next/head";
import { Flex, Title } from "@mantine/core";
import { useIsMounted } from "@/lib/hooks";
import { useDynamicContext } from "@dynamic-labs/sdk-react-core";
import LoggedOut from "@/components/LoggedOut";

export default function Home() {
  const isMounted = useIsMounted();
  const { isAuthenticated } = useDynamicContext();

  return (
    <>
      <Head>
        <title>Casa Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction={"column"} w={"100%"} h={"100vh"}>
        {isMounted && (
          <>
            {isAuthenticated ? (
              <Flex
                direction={"column"}
                justify={"center"}
                align={"center"}
                w={"100%"}
                h={"100%"}
              >
                <div>
                  <Title>Listings</Title>
                </div>
              </Flex>
            ) : (
              <LoggedOut />
            )}
          </>
        )}
      </Flex>
    </>
  );
}
