import Head from "next/head";
import { useAccount } from "wagmi";
import { Flex } from "@mantine/core";
import { useIsMounted } from "@/lib/hooks";
import { useDynamicContext } from "@dynamic-labs/sdk-react-core";
import LoggedOut from "@/components/LoggedOut";
import Header from "@/components/Header";

export default function Home() {
  const isMounted = useIsMounted();
  const { address, isConnected, chain } = useAccount();
  const { isAuthenticated } = useDynamicContext();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction={"column"} w={"100%"} h={"100vh"}>
        {isMounted && (
          <>
            <Header />
            {isAuthenticated ? (
              <Flex
                direction={"column"}
                justify={"center"}
                align={"center"}
                w={"100%"}
                h={"100%"}
              >
                <p>wagmi connected: {isConnected ? "true" : "false"}</p>
                <p>wagmi address: {address}</p>
                <p>wagmi network: {chain?.id}</p>
              </Flex>
            ) : (
              <LoggedOut />
            )}
          </>
        )}
      </Flex>
    </>
  );
}
